openapi: 3.0.1
info:
  title: deliveryService
  version: 1.0.0
servers:
- url: //localhost:9098/deliveries
paths:
  /addresses/{key}:
    get:
      operationId: operation1_getBillingAddress
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
    delete:
      operationId: operation1_deleteBillingAddress
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
  /addresses:
    put:
      operationId: operation1_updateBillingAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
          application/xml:
            schema:
              $ref: '#/components/schemas/Address'
        required: false
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
            application/xml:
              schema:
                $ref: '#/components/schemas/Address'
    post:
      operationId: operation1_createBillingAddress
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
          application/xml:
            schema:
              $ref: '#/components/schemas/Address'
        required: false
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
            application/xml:
              schema:
                $ref: '#/components/schemas/Address'
components:
  schemas:
    Address:
      type: object
      properties:
        houseNumber:
          type: integer
          format: int64
          description: The House Number
        street:
          type: string
          description: The Street details of the Address
        postCode:
          type: string
          description: The postCode of the Address
        city:
          type: string
          description: The city of the Address
        key:
          type: string
          description: A key to put the address in to a map (eg. 0005)
      xml:
        name: Address
